version: "3.8"

services:
  
  user-service:
    image: user-service
    container_name: user-service
    restart: always
    ports:
      - "8081:8080"

  channels-api:
    build:
      context: ./channels-api  # Apunta a la carpeta del servicio
      dockerfile: Dockerfile
    container_name: channels-api
    ports:
      - "8086:8086"
    restart: always

  devices-crud:
    build: .
    container_name: devices-crud
    restart: always
    depends_on:
      - db
      - user-service
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: devices_db
      USER_SERVICE_URL: http://user-service:8080/users/email

  image-api:
    build:
      context: ./image-api  # Apunta al directorio de tu código
      dockerfile: Dockerfile
    container_name: image-api
    restart: always
    ports:
      - "8087:8087"  
    environment:
      - PORT=8086
      - CORS_ALLOWED_ORIGINS=*
      - FFMPEG_PATH=/usr/bin/ffmpeg
    volumes:
      - ./image-api:/app  
    depends_on:
      - devices-crud
