version: "3.8"

services:
  user-api:
    image: user-api:latest
    container_name: user-api-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://aurora-cluster-endpoint:3306/tu_base_datos
      SPRING_DATASOURCE_USERNAME: tu_usuario
      SPRING_DATASOURCE_PASSWORD: tu_contraseña
    networks:
      - microservices-network
  auth-api:
    image: auth-api:latest
    container_name: auth-api-container
    restart: always
    depends_on:
      - user-api
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: "superclaveultrasecreta"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
